/*
 * Autogenerated header by File Header Comment extension - Donna Iwan
 * File:       global_providers.dart
 * Created on: Fri Jul 08 2022
 * Author:     Nguyen Huu Nghi
 *
 * Copyright (c) 2022 Nguyen Huu Nghi
 *
 * Description 
 */
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'services/network_services/network_services.dart';

///Network status provider
final connectivityProvider = FutureProvider.autoDispose<bool>(
  (ref) async {
    final connectivityResult = await NetworkServices.checkConnectivity();
    return connectivityResult;
  },
);
