// ignore_for_file: public_member_api_docs
/*
 * Autogenerated header by File Header Comment extension - Donna Iwan
 * File:       github_users_services_controller.dart
 * Created on: Fri Jul 08 2022
 * Author:     Nguyen Huu Nghi
 *
 * Copyright (c) 2022 Nguyen Huu Nghi
 *
 * Description 
 */

import '../../model/github_user.dart';
import '../../utils/utilities.dart';
import 'github_users_services.dart';

class GitHubUsersServicesController {
  GitHubUsersServicesController({
    required this.remote,
    required this.local,
  });
  final GitHubUsersServices remote;
  final GitHubUsersServices local;

  Future<List<GitHubUser>> getAllUsersRecords({
    bool forceRefresh = false,
    bool offline = false,
  }) {
    if (!offline) {
      Utils.log(title: 'REFRESH', info: 'Get new users from remote records.');

      return remote.getAllUsersRecords(forceRefresh: forceRefresh);
    } else {
      Utils.log(title: 'REFRESH', info: 'Get new users from local.');

      return local.getAllUsers();
    }
  }

  Future<GitHubUser?> getUserInfoRecords({
    required GitHubUser user,
    bool forceRefresh = false,
    bool offline = false,
  }) {
    if (!offline) {
      return remote.getUserInfoRecords(
        user: user,
        forceRefresh: forceRefresh,
      );
    } else {
      return local.getUserInfo(user.login ?? '');
    }
  }
}
